### ISSUE TITLE
Patch Release (0.15.3) Breaks Local Development Setup

### ISSUE THREAD

**Issue by alexbeattie42** [livekit/livekit-server#422]
**Describe the bug**
Going from v0.15.2 to v0.15.3 and [accompanying docs change](https://github.com/livekit/livekit-docs/commit/9b744948351dd4fc1a8a7b19bf800442e80ea652) breaks the local development setup.
Attempting to connect to the server produces `error could not connect after timeout` on the client and server producing
`server closing WS connection`

**Server**
- Version: [0.15.3]
- Environment: local dev
- docker-compose

**Client**
- https://example.livekit.io/#/

**To Reproduce**
1. Create a livekit server with the follwing docker-compose container
```
  livekit-server:
    image: livekit/livekit-server:v0.15.3
    env_file:
      - .env
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    command: livekit-server --dev --node-ip=host.docker.internal
```
The env file contains the line:
`LIVEKIT_KEYS="KEY: SECRET"`

**Expected behavior**
The server should still function without configuration changes as in 0.15.2 since 0.15.3 is a patch release.

**Screenshots**
<img width="843" alt="Screen Shot 2022-02-08 at 4 27 30 PM" src="https://user-images.githubusercontent.com/30098201/153086214-c0a7e9bf-e2d1-412a-bd59-b226eaaa0d5e.png">

**Additional context**
The changes [made here](https://github.com/livekit/livekit-docs/commit/9b744948351dd4fc1a8a7b19bf800442e80ea652) are breaking (at least in relation to local development) and should be noted as such. The documentation for working with <=0.15.2 should be maintained and a guide for migrating to 0.15.3 should be included
