### ISSUE TITLE
Turn connection not established inside a docker network

### ISSUE THREAD

**Issue by avvertix** [livekit/livekit-server#679]
**Describe the bug**

Currently the turn ports used to allow relaying clients streams https://github.com/livekit/livekit-server/blob/a1caeeb8de8a6a6d5c6328195c4c6cb1567d18a4/pkg/service/turn.go are established randomly and in a port range. This range is not configurable.

Considering that in the setup I'm using a Docker network with port mapping that range create problems as I cannot map all those ports. I understand that network host mode should be preferred, but since (if I'm correct) all binding are done on 0.0.0.0 I cannot do that as I already have port 443 occupied and I cannot move the service that is using it, so I wanted to apply reverse proxy to all tcp connections to port 443 and then map the ports as I cannot connect two containers to the hosted network and to the proxy network at the same time.

Here probably the real question is: would you be willing to accept a pull request to make those ports configurable? Do you have plans to allow those ports to be configurable? Can those ports be limited to one or two or will have impact to clients?

In any case below all the configuration files I used and the docker compose setup I'm trying to achieve

**Server**
- Version: 0.15.7
- Environment: VPS, Docker
- using docker network with port mapping

**Client**
- SDK: https://livekit.io/connection-test

**To Reproduce**
1. two clients are connected to room
2. 3rd client joins
3. 3rd client does '...'

**Expected behavior**

**Screenshots**

**Additional context**

For reference I'm adding here the docker compose file I'm using and the configuration values with redacted sensible data

**docker-compose.yaml**

```yaml
## Modified version of LiveKit's docker-compose to use local networks
## and to expose http/https services behind Traefik

version: '3.9'

networks:
  internal:
  web:
    external:
      name: reverseproxy_traefik_web


services:

  livekit:
    image: livekit/livekit-server:v0.15.7
    command: --config /etc/livekit.yaml --node-ip *****
    restart: unless-stopped
    networks:
      - internal
      - web
    ports:
      - "7881:7881"
      - "7882:7882/udp"
      - "443:443/udp"
    depends_on:
      - redis
    volumes:
      - ./configuration/livekit.yaml:/etc/livekit.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lk.rule=Host(`lk.domain.example`)"
      - "traefik.http.routers.lk.entrypoints=websecure"
      - "traefik.http.routers.lk.tls=true"
      - "traefik.http.routers.lk.tls.certresolver=mytls"
      - "traefik.http.routers.lk.service=meet-de"
      - "traefik.http.services.lk.loadbalancer.server.port=7880"
      

  turn:
    image: nginx:1.21.6-alpine
    restart: unless-stopped
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - internal
      - web
    volumes:
      - "./configuration/turn-nginx.conf:/etc/nginx/nginx.conf:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.turn-tcp.rule=HostSNI(`turn.domain.example`)"
      - "traefik.tcp.routers.turn-tcp.entrypoints=websecure"
      - "traefik.tcp.routers.turn-tcp.tls=true"
      - "traefik.tcp.routers.turn-tcp.tls.certresolver=mytls"
      - "traefik.tcp.routers.turn-tcp.service=turn-proxy"
      - "traefik.tcp.services.turn-proxy.loadbalancer.server.port=5349"

  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    networks:
      - internal
    volumes:
      - ./configuration/redis.conf:/etc/redis.conf
```

**livekit.yaml**

```yaml
port: 7880

logging:
    level: debug

rtc:
    tcp_port: 7881
    udp_port: 7882
    use_external_ip: true
redis:
    address: redis:6379
    username: ""
    password: ""
    db: 0
turn:
    enabled: true
    domain: turn.domain.example
    cert_file: ""
    key_file: ""
    tls_port: 5349
    udp_port: 443
    external_tls: true
keys:
    redacted: redacted
```

turn-nginx.conf

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream {

    upstream lk {
        server livekit:5349;
    }

    server {
        listen 5349;

        proxy_ssl off;
        proxy_pass lk;
        proxy_connect_timeout 20s;
        proxy_buffer_size 10m;

    }

}
```

**redis.conf**

```
bind 0.0.0.0
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300
```
